#!/usr/bin/env bash
# Displays Best School 10 times and says Hi on iteration 9

i=1

while [ "$i" -le 10 ]
do
    echo "Best School"

    if [ "$i" -eq 9 ]
    then
        echo "Hi"
    fi

    i=$((i + 1))
done
